# Generated by Django 5.1.3 on 2025-03-28 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField()),
                ('is_completed_by_faculty', models.BooleanField(default=False)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='tasks', to='users.faculty')),
                ('prerequisite_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OtherEmployee',
            fields=[
                ('other_employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('job_role', models.CharField(max_length=255)),
                ('other_employee_dept', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('office_room', models.CharField(max_length=20)),
                ('associated_tasks', models.ManyToManyField(blank=True, to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.faculty')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            options={
                'unique_together': {('faculty', 'task')},
            },
        ),
    ]
