# Generated by Django 5.1.3 on 2025-03-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_completed_by_faculty',
            field=models.BooleanField(default=False),
        ),
    ]
