# Generated by Django 5.1.3 on 2025-03-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="completed_by",
        ),
        migrations.AlterUniqueTogether(
            name="taskprogress",
            unique_together={("faculty", "task")},
        ),
        migrations.AddField(
            model_name="taskprogress",
            name="completed",
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name="taskprogress",
            name="progress_status",
        ),
    ]
