# Generated by Django 5.1.3 on 2025-02-18 23:20

import django.db.models.deletion
from django.db import migrations, models


def create_faculty_table(apps, schema_editor):
    # Check if the database table already exists
    table_names = schema_editor.connection.introspection.table_names()
    if "tasks_faculty" not in table_names:
        # if the table does not exist, create it
        Faculty = apps.get_model("tasks", "Faculty")
        schema_editor.create_model(Faculty)
    else:
        # if it does exist, do nothing
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_prerequisite_task"),
    ]

    operations = [
        migrations.RunPython(create_faculty_table),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "faculty_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tasks.faculty",
                    ),
                ),
                ("permissions", models.CharField(max_length=255)),
            ],
            bases=("tasks.faculty",),
        ),
        migrations.CreateModel(
            name="FacultyDocument",
            fields=[
                ("document_id", models.AutoField(primary_key=True, serialize=False)),
                ("file_path", models.CharField(max_length=255)),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.faculty"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OtherEmployee",
            fields=[
                (
                    "other_employee_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("job_role", models.CharField(max_length=255)),
                ("other_employee_dept", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("phone", models.CharField(max_length=10)),
                ("office_room", models.CharField(max_length=20)),
                (
                    "associated_tasks",
                    models.ManyToManyField(blank=True, to="tasks.task"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskProgress",
            fields=[
                ("progress_id", models.AutoField(primary_key=True, serialize=False)),
                ("progress_status", models.CharField(max_length=255)),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.faculty"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.task"
                    ),
                ),
            ],
        ),
    ]
