# Generated by Django 5.1.7 on 2025-03-19 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_is_completed_by_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otheremployee',
            name='associated_tasks',
        ),
        migrations.DeleteModel(
            name='FacultyDocument',
        ),
        migrations.DeleteModel(
            name='OtherEmployee',
        ),
    ]
