# Generated by Django 5.1.7 on 2025-03-19 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_facultydocument_faculty'),
        ('tasks', '0003_remove_otheremployee_associated_tasks_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskprogress',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.faculty'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='users.faculty'),
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
