# Generated by Django 5.1.3 on 2025-02-20 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_faculty_admin_facultydocument_otheremployee_and_more"),
        ("tasks", "0004_alter_faculty_user"),
    ]

    operations = []
