# Generated by Django 5.1.7 on 2025-03-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_taskprogress_faculty_alter_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherEmployee',
            fields=[
                ('other_employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('job_role', models.CharField(max_length=255)),
                ('other_employee_dept', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('office_room', models.CharField(max_length=20)),
                ('associated_tasks', models.ManyToManyField(blank=True, to='tasks.task')),
            ],
        ),
    ]
