# Generated by Django 5.1.3 on 2025-02-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_prerequisite_task"),
        ("tasks", "0004_alter_faculty_user"),
    ]

    operations = []
