# Generated by Django 5.1.3 on 2025-02-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_otheremployee_associated_tasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='taskprogress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
