# Generated by Django 5.1.3 on 2025-05-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultydocument',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
