services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/local/app
      - media_data:/usr/local/app/media:rw
    depends_on:
      db:
        condition: service_healthy
    environment:
      DJANGO_SETTINGS_MODULE: smse_onboarding.settings
      DATABASE_URL: postgres://postgres:password@db:5432/smse-db
      DB_HOST: db
      DOCKERIZED: "1"
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@gmail.com
      DJANGO_SUPERUSER_PASSWORD: password
    command: >
      bash -c "
             python manage.py migrate &&
             python manage.py loaddata fixtures/test_data.json || true &&
             python manage.py createsuperuser --noinput --username=admin --email=admin@gmail.com || true &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smse-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  media_data: