# Generated by Django 5.1.3 on 2025-03-19 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('job_role', models.CharField(max_length=255)),
                ('engineering_dept', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('zoom_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('office_room', models.CharField(max_length=20)),
                ('hire_date', models.DateTimeField()),
                ('mailing_list_status', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True)),
                ('completed_onboarding', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
