# Generated by Django 5.1.3 on 2025-04-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='last_welcome_shown',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
