# Generated by Django 5.1.3 on 2025-05-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_faculty_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
