# Generated by Django 5.1.3 on 2025-04-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
