# Generated by Django 5.1.3 on 2025-04-30 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_reminder_title_alter_reminder_message'),
        ('users', '0002_faculty_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='secondary_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_reminders', to='users.faculty'),
        ),
    ]
