name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: smse
          POSTGRES_PASSWORD: password
          POSTGRES_DB: SMSE_Onboarding

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django
        pip install -r requirements.txt
        pip install autopep8 isort autoflake
        
    - name: Auto-fix code formatting
      run: |
        autoflake --remove-all-unused-imports --in-place --recursive .
        isort .
        autopep8 --in-place --aggressive --recursive .

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .

    - name: Run Migrations
      env:
        DATABASE_URL: psql postgres://postgres:password@localhost:5432/smse-db
      run: |
        cd smse_onboarding_main_project
        python manage.py makemigrations
        python manage.py migrate
        
    - name: Run Tests
      run: |
        cd smse_onboarding_main_project
        python manage.py test
